apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base/config
- ../../base/services
- ../../base/deployments

patches:
- path: ./patches/hpa-patch.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: web-deployment-hpa
- path: ./patches/resource-patch.yaml
- path: ./patches/finance-system-prod-config.yaml
  