apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base/config
- ../../base/services
- ../../base/deployments

patches:
- path: ./patches/ingress-url-patch.yaml
  target:
    kind: Ingress